-- SRCTYPE

INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('AIFS', 'AIFS', 'AIFS', 'AIFS', 'AIFS', 'AIFS', NULL, NULL, NULL, NULL,
    NULL, 'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('ASCII0', 'ASCII0', 'ASCII0 input converter', 'ASCII0 input converter',
    'ASCII0 input converter', 'ASCII0 input converter', NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('CACHE', 'CACHE', 'Cache CDR source', 'Caceh CDR Datenquelle', 'Cache CDR',
    'Cache CDR', NULL, NULL, NULL, NULL, NULL, 'ADMIN', NULL, NULL, NULL, NULL,
    NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('CCNDC', 'CCNDC', 'Operator CCNDC', 'Operator CCNDC', 'Operator CCNDC',
    'Operator CCNDC', NULL, NULL, NULL, NULL, 'TOC', 'ADMIN', NULL, NULL, NULL,
    NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('DUOB', 'DUOB', 'DuoBill Customer flat file from SIS',
    'DuoBill Kunden-Datei von SIS', 'DuoBill', 'DuoBill', NULL, NULL, NULL, NULL
    , NULL, 'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('ISRV', 'MB', 'Message Broker / MVP', 'Message Broker / MVP', NULL, NULL,
    NULL, NULL, NULL, NULL, 'IPC', 'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('M2M', 'M2M', 'M2M', 'M2M', 'M2M', 'M2M', NULL, NULL, NULL, NULL, NULL,
    'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('MBLOGPROC', 'MBLOGPROC', 'Message Broker LogWriter CPU Consumption',
    'Message Broker LogWriter CPU Consumption',
    'Message Broker LogWriter CPU Consumption',
    'Message Broker LogWriter CPU Consumption', NULL, NULL, NULL, NULL, NULL,
    'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('MBPROC', 'MBPROC', 'Message Broker CPU Consumption',
    'Message Broker CPU Consumption', 'Message Broker CPU Consumption',
    'Message Broker CPU Consumption', NULL, NULL, NULL, NULL, NULL, 'ADMIN',
    NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('MBQUEUE', 'MBQUEUE', 'Message Broker Message Queue Size',
    'Message Broker Message Queue Size', 'Message Broker Message Queue Size',
    'Message Broker Message Queue Size', NULL, NULL, NULL, NULL, NULL, 'ADMIN',
    NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('MBS', '05', 'MBS', 'MBS', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('MCCMNC', 'MCCMNC', 'Operator MCCMNC', 'Operator MCCMNC', 'Operator MCCMNC'
    , 'Operator MCCMNC', NULL, NULL, NULL, NULL, 'TOC', 'ADMIN', NULL, NULL,
    NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('MMSB', 'MBB', 'Multimedia Messaging Service Bulk',
    'Multimedia Messaging Service Bulk', 'Multimedia Messaging Service Bulk',
    'Multimedia Messaging Service Bulk', NULL, NULL, NULL, NULL, NULL, 'ADMIN',
    NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('MMSC', 'MMSC', 'Multimedia Messaging Service Center',
    'Multimedia Messaging Service Center', 'Multimedia Messaging Service Center'
    , 'Multimedia Messaging Service Center', NULL, NULL, NULL, NULL, 'MLC',
    'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('MSC', 'MSC', 'MSC', 'MSC', 'MSC', 'MSC', NULL, NULL, NULL, NULL, NULL,
    'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('MVS', 'MVS', 'MVS', 'MVS', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('OPER', 'OPER', 'OPER', 'OPER', 'OPER', 'OPER', NULL, NULL, NULL, NULL,
    'TOC', 'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('OTA', 'OTA', 'OTA', 'OTA', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('POS', 'MPS', 'MPS UFIH Import', 'MPS UFIH Import', 'MPS UFIH Import',
    'MPS UFIH Import', NULL, NULL, NULL, NULL, NULL, 'ADMIN', NULL, NULL, NULL,
    NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('SDC', '02', 'SDC', 'SDC', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('SMSC', 'SMSC', 'Old SMSC (Acision)', 'Altes SMSC (Acision)',
    'Old SMSC (Acision)', 'Old SMSC (Acision)', NULL, NULL, NULL, NULL, 'LAC',
    'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('SMSN', 'SMSN', 'New SMSC (OMN)', 'Neues SMSC (OMN)', 'New SMSC (OMN)',
    'New SMSC (OMN)', NULL, NULL, NULL, NULL, 'LAC', 'ADMIN', NULL, NULL, NULL,
    NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('STAN', 'STAN', 'St. Anton Content Services', 'St. Anton Content Dienste',
    'St. Anton Services', 'St. Anton Services', NULL, NULL, NULL, NULL, NULL,
    'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('TPIDN', 'TPIDN', 'TPI Delivery Notifications',
    'TPI Delivery Notifications', 'TPI Delivery Notifications',
    'TPI Delivery Notifications', NULL, NULL, NULL, NULL, NULL, 'ADMIN', NULL,
    NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('TPIREQ', 'TPIREQ', 'TPI Submit Request', 'TPI Submit Request',
    'TPI Submit Request', 'TPI Submit Request', NULL, NULL, NULL, NULL, NULL,
    'ADMIN', NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    SRCTYPE (
        SRCT_ID, SRCT_CODE, SRCT_LANG01, SRCT_LANG02, SRCT_LANG03, SRCT_LANG04,
        SRCT_VALUE1, SRCT_VALUE2, SRCT_VALUE3, SRCT_VALUE4, SRCT_CONTID,
        SRCT_RESPACID, SRCT_TEXT1LANG02, SRCT_TEXT2LANG02, SRCT_OPERNOT,
        SRCT_CCNOT, SRCT_MARNOT)
VALUES
    ('VASP', '01', 'VASP', 'VASP', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    'ADMIN', NULL, NULL, NULL, NULL, NULL);

--MAPTYPE

INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('VASP', '01', 'VASP', 'VASP', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('SMSC', '02', 'SMSC', 'SMSC', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('CUCA', '03', 'CUCA', 'CUCA', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('MBS', '04', 'Micro Billing Server', 'Micro Billing Server', NULL, NULL,
    NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('ISRV', '05', 'I-Server', 'I-Server', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('AIFI01', '07', 'AIFI01', 'AIFI01', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('OPER', '08', 'Operator Import', 'Operator Import', NULL, NULL, NULL, NULL,
    NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('MSC', '09', 'MSC', 'MSC', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('MMSC', 'MMSC', 'Multimedia Messaging Service Center',
    'Multimedia Messaging Service Center', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('AAABULK', 'AAABULK', 'Fast Track AAA Bulk Provisioning',
    'Fast Track AAA Bulk Provisioning', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('AAAUFIH', 'AAAUFIH', 'POS UFIH Input for AAA', 'POS UFIH Input for AAA',
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('MCCMNC', 'MCCMNC', 'MCC MNC Import', 'MCC MNC Import', NULL, NULL, NULL,
    NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('MEC', 'MEC', 'MEC', 'MEC', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('OTA', 'OTA', 'OTA', 'OTA', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('POS', 'POS', 'Mobile Payment System (MPS/POS)',
    'Mobile Payment System (MPS/POS)', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('DUOBILL', 'DUOBILL', 'DuoBill Mapping Table Import',
    'DuoBill Flat File Import', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('MMSB', 'MMSB', 'Bulk Multimedia Message SC', 'Bulk Multimedia Message SC',
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('STAN', 'STAN', 'St. Anton Content Services', 'St. Anton Content Dienste',
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('TPIREQ', 'TPIREQ', 'TPI Submit Request', 'TPI Submit Request', NULL, NULL,
    NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('TPIDN', 'TPIDN', 'TPI Delivery Notifications',
    'TPI Delivery Notifications', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('MBPROC', 'MBPROC', 'Message Broker CPU Consumption',
    'Message Broker CPU Consumption', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('MBQUEUE', 'MBQUEUE', 'Message Broker Message Queue Size',
    'Message Broker Message Queue Size', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('MBLOGPROC', 'MBLOGPROC', 'Message Broker LogWriter CPU Consumption',
    'Message Broker LogWriter CPU Consumption', NULL, NULL, NULL, NULL, NULL,
    NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('ASCII0', 'ASCII0', 'ASCII0 input converter', 'ASCII0 input converter',
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPTYPE (
        MAPT_ID, MAPT_CODE, MAPT_LANG01, MAPT_LANG02, MAPT_LANG03, MAPT_LANG04,
        MAPT_VALUE1, MAPT_VALUE2, MAPT_VALUE3, MAPT_VALUE4)
VALUES
    ('CSV', 'CSV', 'CSV input converter', 'CSV input converter', NULL, NULL,
    NULL, NULL, NULL, NULL);


-- INDEXSTATE

INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('MEC', 'D', 'MEC-D', 'MEC indexing done', 'MEC Indexierung erledigt', NULL,
    NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('MEC', 'E', 'MEC-E', 'MEC indexing error', 'MEC Indexierung fehlerhaft',
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('MEC', 'S', 'MEC-S', 'MEC Scheduled for INdexing',
    'MEC geplant fuer indexing', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH30', 'D', 'SMCH30-D', 'SMSC30 Indexing done',
    'SMSC30 Indexierung erledigt', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH30', 'E', 'SMCH30-E', 'SMSC30 Indexing error',
    'SMSC30 Indexierung fehlerhaft', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH30', 'S', 'SMCH30-S', 'SMSC30 Indexing scheduled',
    'SMSC30 Indexierung geplant', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH80', 'D', 'SMCH80-D', 'SMSC80 Indexing done',
    'SMSC80 Indexierung erledigt', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH80', 'E', 'SMCH80-E', 'SMSC80 Indexing error',
    'SMSC80 Indexierung fehlerhaft', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH80', 'S', 'SMCH80-S', 'SMSC80 Indexing scheduled',
    'SMSC80 Indexierung geplant', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH90', 'D', 'SMCH90-D', 'SMSC90 Indexing done',
    'SMSC90 Indexierung erledigt', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH90', 'E', 'SMCH90-E', 'SMSC90 Indexing error',
    'SMSC90 Indexierung fehlerhaft', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH90', 'S', 'SMCH90-S', 'SMSC90 Indexing scheduled',
    'SMSC90 Indexierung geplant', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('MMSC', 'D', 'MMSC-D', 'MMSC indexing done', 'MMSC Indexierung erledigt',
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('MMSC', 'E', 'MMSC-E', 'MMSC indexing error', 'MMSC Indexierung fehlerhaft'
    , NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('MMSC', 'S', 'MMSC-S', 'MMSC Scheduled for INdexing',
    'MMSC geplant fuer indexing', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('MMSB', 'D', 'MMSB-D', 'MMSB indexing done', 'MMSB Indexierung erledigt',
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('MMSB', 'E', 'MMSB-E', 'MMSB indexing error', 'MMSB Indexierung fehlerhaft'
    , NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('MMSB', 'S', 'MMSB-S', 'MMSB Scheduled for INdexing',
    'MMSB geplant fuer indexing', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH20', 'S', 'SMCH20-S', 'SMSC20 Indexing scheduled',
    'SMSC20 Indexierung geplant', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH20', 'E', 'SMCH20-E', 'SMSC20 Indexing error',
    'SMSC20 Indexierung fehlerhaft', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH20', 'D', 'SMCH20-D', 'SMSC20 Indexing done',
    'SMSC20 Indexierung erledigt', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH10', 'S', 'SMCH10-S', 'SMSC10 Indexing scheduled',
    'SMSC10 Indexierung geplant', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH10', 'E', 'SMCH10-E', 'SMSC10 Indexing error',
    'SMSC10 Indexierung fehlerhaft', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    INDEXSTATE (
        INDEXS_MAPID, INDEXS_ID, INDEXS_CODE, INDEXS_LANG01, INDEXS_LANG02,
        INDEXS_LANG03, INDEXS_LANG04, INDEXS_VALUE1, INDEXS_VALUE2,
        INDEXS_VALUE3, INDEXS_VALUE4)
VALUES
    ('SMCH10', 'D', 'SMCH10-D', 'SMSC10 Indexing done',
    'SMSC10 Indexierung erledigt', NULL, NULL, NULL, NULL, NULL, NULL);


--MAPPING

INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMSC', 'SMSC', 'ASCII0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, 0, 'MAY_USE_MONTH_PARTITIONS', 'SMSC', NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('VASP', 'VASP', 'VASP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('CUCA', 'CUCA', 'CUCA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('MBS', 'MBS', 'MBS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    0, NULL, 'SMSC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('ISRV', 'ISRV', 'ASCII0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, 0, 'MAY_USE_BDETAIL_PARTITIONS', 'ISRV', NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('OTA', 'OTA', 'OTA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('OPER', 'Operator Import', 'OPER', NULL, NULL, NULL, NULL, NULL, NULL, NULL
    , NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('MSC', 'MSC', 'ASCII0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, 1, 'MAY_USE_MONTH_PARTITIONS', 'MSC', NULL, NULL, NULL, NULL, NULL,
    TO_DATE('06.05.2019 14:34:06', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '06.05.2019 14:34:06', 'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('MMSC', 'Multimedia Messaging Service C', 'ASCII0', NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, 1, 'MAY_USE_MONTH_PARTITIONS', 'MMSC', NULL,
    NULL, NULL, NULL, NULL, TO_DATE('28.05.2019 11:19:05',
    'DD.MM.YYYY HH24:MI:SS'), TO_DATE('28.05.2019 11:19:06',
    'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('AAABULK', 'Fast Track AAA', 'AAABULK', NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('AAAUFIH', 'POS UFIH Input for AAA', 'AAAUFIH', NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('MCCMNC', 'MCC MNC Number Range Import', 'CSV', NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, 1, NULL, 'MCCMNC', NULL, 'DAILY', NULL, 5, 0,
    TO_DATE('28.11.2018 12:33:57', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '28.11.2018 12:33:58', 'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('MEC', 'MEC', 'MEC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('POS', 'Mobile Payment System', 'POS', NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('DUOBILL', 'DUOBILL', 'DUOBILL', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('MMSB', 'MMSB', 'ASCII0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, 0, 'MAY_USE_MONTH_PARTITIONS', 'MMSB', NULL, NULL, NULL, NULL, NULL,
    TO_DATE('08.11.2010 18:58:50', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '08.11.2010 18:58:51', 'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('STAN', 'St. Anton Content Services', 'ASCII0', 'STAN-########', 6, 8, NULL
    , NULL, NULL, NULL, NULL, NULL, 1, 'MAY_USE_MONTH_PARTITIONS', 'STAN', NULL,
    NULL, NULL, NULL, NULL, TO_DATE('30.05.2019 23:12:55',
    'DD.MM.YYYY HH24:MI:SS'), TO_DATE('30.05.2019 23:12:55',
    'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('TPIREQ', 'TPI Submit Request', 'TPIREQ', NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 0, NULL, 'TPIREQ', NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('TPIDN', 'TPI Delivery Notifications', 'TPIDN', NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, 0, NULL, 'TPIDN', NULL, NULL, NULL, NULL, NULL
    , NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('MBPROC', 'Message Broker CPU Consumption', 'MBPROC', NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'MBPROC', NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('MBQUEUE', 'Message Broker Queue Size', 'MBQUEUE', NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, 0, NULL, 'MBQUEUE', NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('MBLOGPROC', 'MB LogWriter CPU Consumption', 'MBLOGPROC', NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('CCNDC', 'CC NDC Number Range Import', 'CSV', NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 1, NULL, 'CCNDC', NULL, 'DAILY', NULL, 5, 0, TO_DATE
    ('28.11.2018 12:33:23', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '28.11.2018 12:33:57', 'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH80', 'SMCH80', 'ASCII0', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, 1, 'MAY_USE_MONTH_PARTITIONS', 'SMSC', NULL, NULL, NULL, NULL,
    NULL, TO_DATE('08.11.2016 17:38:06', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '08.11.2016 17:38:06', 'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH90', 'SMCH90', 'ASCII0', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, 1, 'MAY_USE_MONTH_PARTITIONS', 'SMSC', NULL, NULL, NULL, NULL,
    NULL, TO_DATE('08.11.2016 17:38:42', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '08.11.2016 17:38:42', 'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('MBS_CO', 'MBS_CO', 'ASCII0', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, 1, 'MAY_USE_MONTH_PARTITIONS', 'ISRV', NULL, NULL, NULL, NULL,
    NULL, TO_DATE('20.05.2019 14:30:05', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '20.05.2019 14:30:05', 'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('MBS_MO', 'MBS_MO', 'ASCII0', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, 1, 'MAY_USE_MONTH_PARTITIONS', 'ISRV', NULL, NULL, NULL, NULL,
    NULL, TO_DATE('20.05.2019 15:51:54', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '20.05.2019 15:51:54', 'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH30', 'SMCH30', 'ASCII0', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, 1, 'MAY_USE_MONTH_PARTITIONS', 'SMSN', NULL, NULL, NULL, NULL,
    NULL, TO_DATE('31.05.2019 09:45:49', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '31.05.2019 09:45:49', 'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('MVP_CO', 'MVP_CO', 'ASCII0', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, 1, 'MAY_USE_MONTH_PARTITIONS', 'ISRV', NULL, NULL, NULL, NULL,
    NULL, TO_DATE('17.04.2019 08:03:24', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '17.04.2019 08:03:24', 'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH11', 'SMCH11', 'ASCII0', 'SMCH11_########_??????????????.CSV', 8, 8,
    'CONTROL21', 'SMSC CONTROL21', 0, 30, 30, NULL, 1, NULL, 'SMSN', NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH12', 'SMCH12', 'ASCII0', 'SMCH12_########_??????????????.CSV', 8, 8,
    'CONTROL21', 'SMSC CONTROL21', 0, 30, 30, NULL, 1, NULL, 'SMSN', NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH13', 'SMCH13', 'ASCII0', 'SMCH13_########_??????????????.CSV', 8, 8,
    'CONTROL21', 'SMSC CONTROL21', 0, 30, 30, NULL, 1, NULL, 'SMSN', NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH21', 'SMCH21', 'ASCII0', 'SMCH21_########_??????????????.CSV', 8, 8,
    'CONTROL21', 'SMSC CONTROL21', 0, 30, 30, NULL, 1, NULL, 'SMSN', NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH22', 'SMCH22', 'ASCII0', 'SMCH22_########_??????????????.CSV', 8, 8,
    'CONTROL21', 'SMSC CONTROL21', 0, 30, 30, NULL, 1, NULL, 'SMSN', NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH23', 'SMCH23', 'ASCII0', 'SMCH23_########_??????????????.CSV', 8, 8,
    'CONTROL21', 'SMSC CONTROL21', 0, 30, 30, NULL, 1, NULL, 'SMSN', NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH31', 'SMCH31', 'ASCII0', 'SMCH31_########_??????????????.CSV', 8, 8,
    'CONTROL21', 'SMSC CONTROL21', 0, 30, 30, NULL, 1, NULL, 'SMSN', NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH32', 'SMCH32', 'ASCII0', 'SMCH32_########_??????????????.CSV', 8, 8,
    'CONTROL21', 'SMSC CONTROL21', 0, 30, 30, NULL, 1, NULL, 'SMSN', NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH33', 'SMCH33', 'ASCII0', 'SMCH33_########_??????????????.CSV', 8, 8,
    'CONTROL21', 'SMSC CONTROL21', 0, 30, 30, NULL, 1, NULL, 'SMSN', NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH41', 'SMCH41', 'ASCII0', 'SMCH41_########_??????????????.CSV', 8, 8,
    'CONTROL21', 'SMSC CONTROL21', 0, 30, 30, NULL, 1, NULL, 'SMSN', NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH42', 'SMCH42', 'ASCII0', 'SMCH42_########_??????????????.CSV', 8, 8,
    'CONTROL21', 'SMSC CONTROL21', 0, 30, 30, NULL, 1, NULL, 'SMSN', NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH43', 'SMCH43', 'ASCII0', 'SMCH43_########_??????????????.CSV', 8, 8,
    'CONTROL21', 'SMSC CONTROL21', 0, 30, 30, NULL, 1, NULL, 'SMSN', NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('M2M', 'M2M', 'ASCII0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, 1, 'MAY_USE_MONTH_PARTITIONS', 'M2M', NULL, NULL, NULL, NULL, NULL,
    TO_DATE('28.05.2019 15:37:10', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '28.05.2019 15:37:10', 'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH20', 'SMCH20', 'ASCII0', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, 1, 'MAY_USE_MONTH_PARTITIONS', 'SMSN', NULL, NULL, NULL, NULL,
    NULL, TO_DATE('10.05.2019 09:34:21', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '10.05.2019 09:34:24', 'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH10', 'SMCH10', 'ASCII0', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, 1, 'MAY_USE_MONTH_PARTITIONS', 'SMSN', NULL, NULL, NULL, NULL,
    NULL, TO_DATE('10.05.2019 09:32:46', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '10.05.2019 09:32:48', 'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMCH40', 'SMCH40', 'ASCII0', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, 1, 'MAY_USE_MONTH_PARTITIONS', 'SMSN', NULL, NULL, NULL, NULL,
    NULL, TO_DATE('31.05.2019 09:43:30', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '31.05.2019 09:43:30', 'DD.MM.YYYY HH24:MI:SS'), NULL);
INSERT INTO
    MAPPING (
        MAP_ID, MAP_NAME, MAP_ETID, MAP_FILE_MASK, MAP_FS_FIRST_CHAR,
        MAP_FS_CHAR_COUNT, MAP_SOX_CODE, MAP_SOX_NAME, MAP_SOX_REPORT,
        MAP_MAX_PROC_DELAY, MAP_FILE_INTERVAL, MAP_NEXTSEQ, MAP_EXECUTE,
        MAP_CONDITIONALEXEC, MAP_SRCTID, MAP_DEBUG, MAP_PERIODID, MAP_STARTDAY,
        MAP_STARTHOUR, MAP_STARTMINUTE, MAP_DATETRY, MAP_DATEDONE,
        MAP_ENDCLEARANCE)
VALUES
    ('SMSB01', 'SMSB01', 'ASCII0',
    'SMBRK_vimapmo?-smsb0?.it.bwns.ch_########_?????????????.ascii', 34, 8,
    'CONTROL21', 'SMSC CONTROL21', 0, 30, 30, NULL, 1,
    'MAY_USE_MONTH_PARTITIONS', 'SMSN', NULL, NULL, NULL, NULL, NULL, TO_DATE(
    '17.04.2019 08:03:36', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE(
    '17.04.2019 08:03:36', 'DD.MM.YYYY HH24:MI:SS'), NULL);


-- BIHSTATE

INSERT INTO
    BIHSTATE (
        BIHS_ID, BIHS_CODE, BIHS_LANG01, BIHS_LANG02, BIHS_LANG03, BIHS_LANG04,
        BIHS_VALUE1, BIHS_VALUE2, BIHS_VALUE3, BIHS_VALUE4)
VALUES
    ('MAP', '01', 'MAPPING', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    BIHSTATE (
        BIHS_ID, BIHS_CODE, BIHS_LANG01, BIHS_LANG02, BIHS_LANG03, BIHS_LANG04,
        BIHS_VALUE1, BIHS_VALUE2, BIHS_VALUE3, BIHS_VALUE4)
VALUES
    ('ERR', '02', 'ERROR IN RECORDS', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    BIHSTATE (
        BIHS_ID, BIHS_CODE, BIHS_LANG01, BIHS_LANG02, BIHS_LANG03, BIHS_LANG04,
        BIHS_VALUE1, BIHS_VALUE2, BIHS_VALUE3, BIHS_VALUE4)
VALUES
    ('ERF', '03', 'ERROR IN FILE', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    BIHSTATE (
        BIHS_ID, BIHS_CODE, BIHS_LANG01, BIHS_LANG02, BIHS_LANG03, BIHS_LANG04,
        BIHS_VALUE1, BIHS_VALUE2, BIHS_VALUE3, BIHS_VALUE4)
VALUES
    ('RDY', '04', 'READY', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    BIHSTATE (
        BIHS_ID, BIHS_CODE, BIHS_LANG01, BIHS_LANG02, BIHS_LANG03, BIHS_LANG04,
        BIHS_VALUE1, BIHS_VALUE2, BIHS_VALUE3, BIHS_VALUE4)
VALUES
    ('IDX', '05', 'INDEXED', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    BIHSTATE (
        BIHS_ID, BIHS_CODE, BIHS_LANG01, BIHS_LANG02, BIHS_LANG03, BIHS_LANG04,
        BIHS_VALUE1, BIHS_VALUE2, BIHS_VALUE3, BIHS_VALUE4)
VALUES
    ('IDE', '06', 'Error Indexed', 'Error Indexed', NULL, NULL, NULL, NULL, NULL
    , NULL);
INSERT INTO
    BIHSTATE (
        BIHS_ID, BIHS_CODE, BIHS_LANG01, BIHS_LANG02, BIHS_LANG03, BIHS_LANG04,
        BIHS_VALUE1, BIHS_VALUE2, BIHS_VALUE3, BIHS_VALUE4)
VALUES
    ('idx', '07', 'partially indexed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO
    BIHSTATE (
        BIHS_ID, BIHS_CODE, BIHS_LANG01, BIHS_LANG02, BIHS_LANG03, BIHS_LANG04,
        BIHS_VALUE1, BIHS_VALUE2, BIHS_VALUE3, BIHS_VALUE4)
VALUES
    ('ide', '08', 'error partially indexed', NULL, NULL, NULL, NULL, NULL, NULL,
    NULL);
